### PR TITLE
global: update completion for ES5

### PR DESCRIPTION
**Pull request by szymonlopaciuk**

### CODE REVIEW

**Comment by david-caro** [comment]
@harunurhan So this sholud go in for the editor to have autocompletion on ES5, if we get it in today/tomorrow morning, we can deploy on qa tomorrow, make sure that it works and deploy to prod on monday, so the time where no bugfixes can go in would be really short.
Do you agree?

**Comment by david-caro** [comment]
In any case, @StellaCh if we don't have auto-complete in the editor for a couple of days for affiliations and experiment (that seem not to work now anyhow), is not a big issue right?

**Comment by StellaCh** [comment]
How many days is a couple of days? ;p

**Comment by david-caro** [comment]
Two, four including the weekend.

**Comment by StellaCh** [comment]
Having it by Monday is ok, currently curators are using the editor for adding affiliations so auto-completion is important for their work.

**Comment by david-caro** [comment]
Well, by the end of monday. Is that still ok?

**Comment by StellaCh** [comment]
OK

**Comment by david-caro** [comment]
@harunurhan you can release it as dev, then we pin the dev in the es5 branch of inspire-next, and the deploy will be smooth

**Comment by michamos** [comment]
isn't the completion payload already supposed to be made forward-compatible thanks to some invenio-magic?
From

**Comment by david-caro** [comment]
Not really, the response from invenio is the bare response from elasticsearch. It might be that we are not using them as it should, but currently is not forward-compatible.

**Comment by harunurhan** [comment]
@david-caro @szymonlopaciuk Just upgrade version manually in `package.json` to `0.13.12-dev.1` and it will be released by travis. 

But `0.13.12` won't be picked  up by `inspire-next` automatically, so we can merge it like this do proper release too.

**Comment by harunurhan** [comment]
@david-caro you can rebase master on your local and do `npm version minor`

**Pull request merged**
