### PR TITLE
toolbar-config: Insertion of toolbar component.Set BASE_URL configura…

### PR DESCRIPTION
**Pull request by zzacharo**
…tion on runtime.
- Creation of toolbar component with a save item component.
- Insert a new config interface `BASE_URL_CONFIG` for retrieving url on runtime.
- Set of "$schema" and "control_number" fields to hidden. Comment out `field_categories.items.properties.term`
  for now for fixing `anyOf` schema issue in record-fixer.service of ng2-json-editor.

Signed-off-by: Zacharias Zacharodimos zacharias.zacharodimos@cern.ch

### CODE REVIEW

**Comment by jmartinm** [comment]
@zzacharo please update this PR to have your latest changes

**Comment by zzacharo** [comment]
@jmartinm i updated this PR with a new commit.

**Comment by jmartinm** [comment]
Looks good. You can `squash` both commits into one - http://stackoverflow.com/a/2568581/890185

**Comment by zzacharo** [comment]
Yes i know but it was a little bit messy this time so i ignored it for now.

**Comment by zzacharo** [comment]
Commits are included in PR #90

**Pull request closed without merging**
