### PR TITLE
Implement adding field from schema feature

### PR DESCRIPTION
**Pull request by harunurhan**
This adds a dropdown which shows possible fields can be added by using schema.

add-field

### CODE REVIEW

**Comment by eamonnmag** [comment]
Very nice @harunurhan

**Comment by kaplun** [comment]
Great! In the hypothesis I am a cataloger without mouse that doesn't want to leave the keyboard, can you make the drop down to activate with a shortcut (these are actually good in general) and allowing me to autocomplete the field so that I can just type few characters in order to enter a new field? Will the dropdown be used also for subfields?

**Comment by harunurhan** [comment]
@kaplun Actually this is the basic implementation, since many things change I didn't want to put a lot of effort. Currently it can be navigated by keyboard arrows. But for keyboard shortcuts I have bigger plans to make it in such way so that it will be so easy to add new shortcuts and configure existing ones without changing the code.

In the example, it adds actually subfields to `author` field. I didn't do adding main fields yet but it will be easy since we have the core component.

**Pull request merged**
