### PR TITLE
upgrade typescript, angular2 and use angular-cli

### PR DESCRIPTION
**Pull request by harunurhan**
* Upgrades typescript to 2.

* Removes angular2-webpack-starter boilerplate related files.

* Adds angular-cli.

* Upgrades ng2-json-editor to latest release.

* Upgrades angular2 to final release (2.0.0).

### CODE REVIEW

**Comment by jmartinm** [comment]
Was trying this PR and I am having an issue with it. Accessing `http://localhost:4200/edit?type=literature&recid=1408160` on [this line](https://github.com/harunurhan/record-editor/blob/9468597629b9af622e3cf47c4f750d33f8567a0f/src/app/editor-container/editor-container.component.ts#L47) the `schema` is not yet fetched (it is of type `Observable`) so afterwards this code crashes:

```javascript
RecordFixerService.prototype.fixRecord = function (rawRecord, schema) {
        var _this = this;
        var record = Object.assign({}, rawRecord);
        Object.keys(record).forEach(function (field) {
            if (!schema['properties'][field]) {
                // Delete if field is not in schema!
                _this.deleteField(record, field);
   
```

since `schema` is undefined.

**Comment by harunurhan** [comment]
@jmartinm it should work because this is almost same as the `example` in `ng2-json-editor`. So I think schema is not fetched correctly. Can you check if fetch record has `$schema`key which is absolute url to schema.

Btw, even if you fix this, it should crash because of `anyOf`

**Comment by jmartinm** [comment]
> @jmartinm it should work because this is almost same as the example in ng2-json-editor. So I think schema is not fetched correctly. Can you check if fetch record has $schemakey which is absolute url to schema.

Everything seems fine, the fetched record has the correct `$schema` URL. [This bit](https://github.com/harunurhan/record-editor/blob/9468597629b9af622e3cf47c4f750d33f8567a0f/src/app/editor-container/editor-container.component.ts#L39-L49) is not very readable so I guess there might be some problem with the Observable not waiting for the `fetchSchema` to finish before assigning the variable.

**Comment by jmartinm** [comment]
As we have just seen, `.properties` needs to be removed from [here](https://github.com/harunurhan/record-editor/blob/9468597629b9af622e3cf47c4f750d33f8567a0f/src/app/shared/services/record.service.ts#L41)

**Comment by jmartinm** [comment]
Are you updating this PR as you make changes? Would be good if you can fix https://github.com/inspirehep/record-editor/pull/81#issuecomment-252858106 to test loading any record and schema.

**Comment by harunurhan** [comment]
fixed travis! @jmartinm

**Comment by jmartinm** [comment]
> fixed travis! @jmartinm

Great! I am testing it now with `invenio-record-editor`

**Pull request merged**
