### PR TITLE
add undo button

### PR DESCRIPTION
**Pull request by harunurhan**
* Adds undo button to undo important changes via ng2-json-editor's
rollbackLastChange.

### CODE REVIEW

**Comment by harunurhan** [comment]
## UI
screen shot 2017-09-05 at 10 30 06

**Comment by StellaCh** [comment]
It needs to be some pixels further from the Save button and closer to the line to avoid clicking on it by mistake

**Comment by harunurhan** [comment]
#### slightly further and centered

screen shot 2017-09-05 at 14 56 42

**Comment by StellaCh** [comment]
Looks better

**Pull request merged**
