### PR TITLE
add help modal

### LINKED ISSUE #220: Help modal with cheatsheet
- [ ] shortcut cheatsheet (key to action mapping)
- [ ]  link to shortcut action definitions (https://inveniosoftware-contrib.github.io/ng2-json-editor/docs/interfaces/_interfaces_custom_shortcut_keys_.customshortcutkeys.html)
- [ ] `$$` reference splitting cheatsheet (character to path mapping)
- [ ] link to schema documentation https://inspire-schemas.readthedocs.io/en/latest/schemas/records/hep.html

### PR DESCRIPTION
**Pull request by harunurhan**
* Resolves #220

#### current UI

screen shot 2017-09-28 at 09 47 03

### CODE REVIEW

**Comment by harunurhan** [comment]
@StellaCh  ui updated!

**Comment by StellaCh** [comment]
- copy should be inversed
- Most of the users use windows. Write ctrl instead of cmd. In the end of the table (before "for more details.."), you can add "For Mac, use command instead of ctrl."
- add a couple more spaces between shortcut and action. Currently, delete and movedown are too close with the shortcuts and it looks too cramped

**Comment by harunurhan** [comment]
- good catch 👍 
- it shows ctrl if you open it on windows. so no problem there.
- agree, we can also put a border between them?

@StellaCh

**Comment by StellaCh** [comment]
A very light grey border could also be fine, try it out and let me know if it looks better

**Pull request merged**
